# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.3.0"

[source]
workspace = "."
paths = ["app/", "database/factories/", "database/seeders/", "tests/"]
includes = ["vendor", "_ide_helper.php"]
excludes = []

[formatter]
preset = "pint"

[linter]
integrations = ["laravel", "pest"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
no-literal-password = { enabled = false }

[analyzer]
plugins = []
excludes = ["tests/"]
ignore = [
    "unhandled-thrown-type",
    "mixed-argument",
    "mixed-method-access",
    "non-existent-method",
    "too-few-arguments",
    "dynamic-static-method-call",
    "possible-method-access-on-null",
    "static-access-on-interface",
    "non-existent-property",
    "no-value",
    "non-documented-property",
    "possibly-undefined-array-index",
    "invalid-return-statement",
    "missing-template-parameter",
]
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
allow-possibly-undefined-array-keys = false
check-throws = true
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = true
check-missing-type-hints = true
register-super-globals = true
